version: '3.4'

services:
  chatgptintegration:
    image: ${DOCKER_REGISTRY-}chatgptintegration
    build:
      context: .
      dockerfile: ChatGPTIntegration/Dockerfile
    ports:
        - 80:80
        - 443:443